### PR TITLE
Add some more specific typespecs and docs

### PR DESCRIPTION
**Pull request by Cantido**
These docs are from my own experimentation with the library, I'm hoping they're correct.

I'd love to help document this library! If you have any requests, I'll be happy to add to this.

### CODE REVIEW

**Comment by mayel** [comment]
@Cantido My apologies, this slipped through the cracks! Thanks for the contribution, I'll resolve conflicts and merge :)

**Comment by mayel** [comment]
@Cantido Merged thanks, much appreciated! I'm curious if you've been able to develop something with it?

**Comment by Cantido** [comment]
I've started to, yeah! But it's in its very early stages, and most of my projects never leave that stage haha. I have barely integrated the federation code and it's not actually federating anything yet. https://github.com/Cantido/chuuni

**Comment by mayel** [comment]
Good luck with it! A lot of interop testing and improvements has been going into the library (now getting a score of 96.6% on the test suite from https://data.funfedi.dev/ :) and hope it proves useful to other projects too...

**Pull request merged**
